<?php
/**
 * @file
 */

/**
 * Implements hook_menu()
 */
function yg_services_cart_menu() {
  $items = array();

  $items['user/wishlist'] = array(
    'page callback' => 'yg_services_cart_view_own_wishlist',
    'access arguments' => array('view own wishlist'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Callback to user/wishlist
 */
function yg_services_cart_view_own_wishlist() {
  global $user;
  if ($user->uid) {
    drupal_goto('user/' . $user->uid . '/wishlist');
  }
}

/**
 * Implements hook_services_resources().
 */
function yg_services_cart_services_resources() {
  $resources = array();

  // Define a resource for ycs consumers
  $resources['yg_services_cart'] = array(
    'actions' => array(

      // Get the orderxml of an order
      'orderxml' => array(
        'file' => array('type' => 'inc', 'module' => 'yg_services_cart', 'name' => 'resources/cart'),
        'help' => t('This method returns the orderxml of an order'),
        'access arguments' => array('administer commerce_order entities'),
        'callback' => 'yg_services_cart_get_orderxml',
        'args' => array(
          array(
            'name' => 'order_id',
            'type' => 'string',
            'description' => t('The order id of the orderxml'),
            'source' => array('path' => 1),
            'optional' => FALSE,
          ),
        ),
      ),
      // Remove an item from the users cart
      'remove_item' => array(
        'file' => array('type' => 'inc', 'module' => 'yg_services_cart', 'name' => 'resources/cart'),
        'help' => t('This method removes an item from a users cart'),
        'access arguments' => array('view any commerce_product entity'),
        'callback' => 'yg_services_cart_remove_item',
        'args' => array(
          array(
            'name' => 'line_item_id',
            'type' => 'string',
            'description' => t('The item id'),
            'source' => array('path' => 1),
            'optional' => FALSE,
          ),
        ),
      ),
      // Add a product to the cart
      'addtocart' => array(
        'file' => array('type' => 'inc', 'module' => 'yg_services_cart', 'name' => 'resources/cart'),
        'help' => t('This method adds a product to the active cart'),
        'access arguments' => array('view any commerce_product entity'),
        'callback' => 'yg_services_cart_addtocart',
        'args' => array(
          array(
            'name' => 'signature',
            'type' => 'array',
            'description' => t('The id of the product'),
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
      // Cancel order
      'cancelorder' => array(
        'file' => array('type' => 'inc', 'module' => 'yg_services_cart', 'name' => 'resources/cart'),
        'help' => t('This method cancels order'),
        'access arguments' => array('view any commerce_product entity'),
        'callback' => 'yg_services_cart_cancel_order',
        'args' => array(
          array(
            'name' => 'order_id',
            'type' => 'string',
            'description' => t('The order id'),
            'source' => array('path' => 1),
            'optional' => FALSE,
          ),
        ),
      ),
      // Add a product to the wishlist
      'addtowishlist' => array(
        'file' => array('type' => 'inc', 'module' => 'yg_services_cart', 'name' => 'resources/cart'),
        'help' => t('This method adds a product to the user wishlist'),
        'access arguments' => array('view any commerce_product entity'),
        'callback' => 'yg_services_cart_addtowishlist',
        'args' => array(
          array(
            'name' => 'signature',
            'type' => 'array',
            'description' => t('The id of the product'),
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
    ),
  );

  return $resources;
}


function yg_services_cart_views_api() {
    return array ('api' => 3);
}

function yg_services_cart_views_default_views() {
  global $conf;
  $lstore_path = $conf['yg']['lstore_path'];
  $vstore_path = $conf['yg']['vstore_path'];
  $bstore_path = $conf['yg']['bstore_path'];
  
    // Check for all view file in views directory
    $view = new view();
    $view->name = 'cart_json';
    $view->description = 'Display a shopping cart update form.';
    $view->tag = 'commerce';
    $view->base_table = 'commerce_order';
    $view->human_name = 'Cart json';
    $view->core = 0;
    $view->api_version = '3.0';
    $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

    /* Display: Defaults */
    $handler = $view->new_display('default', 'Defaults', 'default');
    $handler->display->display_options['title'] = 'Shopping cart';
    $handler->display->display_options['use_ajax'] = TRUE;
    $handler->display->display_options['use_more_always'] = FALSE;
    $handler->display->display_options['access']['type'] = 'none';
    $handler->display->display_options['cache']['type'] = 'none';
    $handler->display->display_options['query']['type'] = 'views_query';
    $handler->display->display_options['query']['options']['query_tags'] = array(
        0 => 'views_commerce_distinct_line_items',
    );
    $handler->display->display_options['exposed_form']['type'] = 'basic';
    $handler->display->display_options['pager']['type'] = 'none';
    $handler->display->display_options['style_plugin'] = 'table';
    $handler->display->display_options['style_options']['columns'] = array(
        'commerce_display_path' => 'commerce_display_path',
        'line_item_title' => 'line_item_title',
        'commerce_unit_price' => 'commerce_unit_price',
        'edit_quantity' => 'edit_quantity',
        'edit_delete' => 'edit_delete',
        'commerce_total' => 'commerce_total',
    );
    $handler->display->display_options['style_options']['default'] = '-1';
    $handler->display->display_options['style_options']['info'] = array(
        'commerce_display_path' => array(
            'sortable' => 0,
            'default_sort_order' => 'asc',
            'align' => '',
            'separator' => '',
        ),
        'line_item_title' => array(
            'align' => '',
            'separator' => '',
        ),
        'commerce_unit_price' => array(
            'sortable' => 0,
            'default_sort_order' => 'asc',
            'align' => '',
            'separator' => '',
        ),
        'edit_quantity' => array(
            'align' => '',
            'separator' => '',
        ),
        'edit_delete' => array(
            'align' => '',
            'separator' => '',
        ),
        'commerce_total' => array(
            'sortable' => 0,
            'default_sort_order' => 'asc',
            'align' => '',
            'separator' => '',
        ),
    );
    /* Relationship: Commerce Order: Referenced line item */
    $handler->display->display_options['relationships']['commerce_line_items_line_item_id']['id'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['relationships']['commerce_line_items_line_item_id']['table'] = 'field_data_commerce_line_items';
    $handler->display->display_options['relationships']['commerce_line_items_line_item_id']['field'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['relationships']['commerce_line_items_line_item_id']['required'] = TRUE;
    /* Relationship: Commerce Line item: Referenced product */
    $handler->display->display_options['relationships']['commerce_product_product_id']['id'] = 'commerce_product_product_id';
    $handler->display->display_options['relationships']['commerce_product_product_id']['table'] = 'field_data_commerce_product';
    $handler->display->display_options['relationships']['commerce_product_product_id']['field'] = 'commerce_product_product_id';
    $handler->display->display_options['relationships']['commerce_product_product_id']['relationship'] = 'commerce_line_items_line_item_id';
    /* Relationship: Commerce Product: Node referencing products from field_product */
    $handler->display->display_options['relationships']['field_product']['id'] = 'field_product';
    $handler->display->display_options['relationships']['field_product']['table'] = 'commerce_product';
    $handler->display->display_options['relationships']['field_product']['field'] = 'field_product';
    $handler->display->display_options['relationships']['field_product']['relationship'] = 'commerce_product_product_id';
    /* Field: Content: LF_ID */
    $handler->display->display_options['fields']['lf_id']['id'] = 'lf_id';
    $handler->display->display_options['fields']['lf_id']['table'] = 'node';
    $handler->display->display_options['fields']['lf_id']['field'] = 'lf_id';
    $handler->display->display_options['fields']['lf_id']['relationship'] = 'field_product';
    $handler->display->display_options['fields']['lf_id']['label'] = '';
    $handler->display->display_options['fields']['lf_id']['exclude'] = TRUE;
    $handler->display->display_options['fields']['lf_id']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['lf_id']['element_wrapper_type'] = '0';
    $handler->display->display_options['fields']['lf_id']['element_default_classes'] = FALSE;
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php']['id'] = 'php';
    $handler->display->display_options['fields']['php']['table'] = 'views';
    $handler->display->display_options['fields']['php']['field'] = 'php';
    $handler->display->display_options['fields']['php']['label'] = '';
    $handler->display->display_options['fields']['php']['exclude'] = TRUE;
    $handler->display->display_options['fields']['php']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php']['php_value'] = '$url_path=\'.$vstore_path.\';
switch ($row->y_store_id) {
  case "yb":
    $url_path = \'.$bstore_path.\';
    break;
  case "yv":
    $url_path = \'.$vstore_path.\';
    break;
  case "yl":
    $url_path = \'.$lstore_path.\';
    break;
}
return $url_path;
';
    $handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php']['php_click_sortable'] = '';
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php_1']['id'] = 'php_1';
    $handler->display->display_options['fields']['php_1']['table'] = 'views';
    $handler->display->display_options['fields']['php_1']['field'] = 'php';
    $handler->display->display_options['fields']['php_1']['label'] = '';
    $handler->display->display_options['fields']['php_1']['exclude'] = TRUE;
    $handler->display->display_options['fields']['php_1']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php_1']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php_1']['php_output'] = '<?php
                                    $sale_price = $data->_field_data[\'commerce_product_field_data_commerce_product_product_id\'][\'entity\']->field_commerce_saleprice[\'und\'][0][\'amount\'];
                                    if ($sale_price) {
                                      $cost_price = number_format($data->_field_data[\'commerce_product_field_data_commerce_product_product_id\'][\'entity\']->commerce_price[\'und\'][0][\'amount\'] * .01, 2, \'.\', \'\');
                                      print \'<div class="views-field-cost-price">$\' . $cost_price . \'</div>\';
                                    }
                                    ?>';
    $handler->display->display_options['fields']['php_1']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php_1']['php_click_sortable'] = '';
    /* Field: Content: Brand */
    $handler->display->display_options['fields']['field_brand']['id'] = 'field_brand';
    $handler->display->display_options['fields']['field_brand']['table'] = 'field_data_field_brand';
    $handler->display->display_options['fields']['field_brand']['field'] = 'field_brand';
    $handler->display->display_options['fields']['field_brand']['relationship'] = 'field_product';
    $handler->display->display_options['fields']['field_brand']['label'] = '';
    $handler->display->display_options['fields']['field_brand']['exclude'] = TRUE;
    $handler->display->display_options['fields']['field_brand']['element_type'] = '0';
    $handler->display->display_options['fields']['field_brand']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_brand']['element_wrapper_type'] = '0';
    $handler->display->display_options['fields']['field_brand']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['field_brand']['type'] = 'taxonomy_term_reference_plain';
    $handler->display->display_options['fields']['field_brand']['delta_offset'] = '0';
    $handler->display->display_options['fields']['field_brand']['field_api_classes'] = TRUE;
    /* Field: Commerce Product: ID */
    $handler->display->display_options['fields']['field_id']['id'] = 'field_id';
    $handler->display->display_options['fields']['field_id']['table'] = 'field_data_field_id';
    $handler->display->display_options['fields']['field_id']['field'] = 'field_id';
    $handler->display->display_options['fields']['field_id']['relationship'] = 'commerce_product_product_id';
    $handler->display->display_options['fields']['field_id']['label'] = '';
    $handler->display->display_options['fields']['field_id']['exclude'] = TRUE;
    $handler->display->display_options['fields']['field_id']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_id']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['field_id']['type'] = 'text_plain';
    $handler->display->display_options['fields']['field_id']['settings'] = array(
        'trim_length' => '600',
    );
    /* Field: Commerce Line Item: Title */
    $handler->display->display_options['fields']['line_item_title']['id'] = 'line_item_title';
    $handler->display->display_options['fields']['line_item_title']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['line_item_title']['field'] = 'line_item_title';
    $handler->display->display_options['fields']['line_item_title']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['line_item_title']['label'] = '';
    $handler->display->display_options['fields']['line_item_title']['exclude'] = TRUE;
    $handler->display->display_options['fields']['line_item_title']['alter']['text'] = 'View product';
    $handler->display->display_options['fields']['line_item_title']['alter']['make_link'] = TRUE;
    $handler->display->display_options['fields']['line_item_title']['alter']['path'] = '[php]/[field_id].html';
    $handler->display->display_options['fields']['line_item_title']['element_label_colon'] = FALSE;
    /* Field: Content: Image */
    $handler->display->display_options['fields']['field_image']['id'] = 'field_image';
    $handler->display->display_options['fields']['field_image']['table'] = 'field_data_field_image';
    $handler->display->display_options['fields']['field_image']['field'] = 'field_image';
    $handler->display->display_options['fields']['field_image']['relationship'] = 'field_product';
    $handler->display->display_options['fields']['field_image']['label'] = '';
    $handler->display->display_options['fields']['field_image']['exclude'] = TRUE;
    $handler->display->display_options['fields']['field_image']['alter']['make_link'] = TRUE;
    $handler->display->display_options['fields']['field_image']['alter']['path'] = '[php]/[field_id].html';
    $handler->display->display_options['fields']['field_image']['element_type'] = '0';
    $handler->display->display_options['fields']['field_image']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_image']['element_wrapper_type'] = '0';
    $handler->display->display_options['fields']['field_image']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['field_image']['click_sort_column'] = 'fid';
    $handler->display->display_options['fields']['field_image']['type'] = 'image_delta';
    $handler->display->display_options['fields']['field_image']['settings'] = array(
        'deltas' => '0',
        'deltas_reversed' => 0,
        'image_style' => 'thumbnail',
        'image_link' => '',
    );
    $handler->display->display_options['fields']['field_image']['delta_offset'] = '0';
    $handler->display->display_options['fields']['field_image']['field_api_classes'] = TRUE;
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php_2']['id'] = 'php_2';
    $handler->display->display_options['fields']['php_2']['table'] = 'views';
    $handler->display->display_options['fields']['php_2']['field'] = 'php';
    $handler->display->display_options['fields']['php_2']['label'] = ' Item and options';
    $handler->display->display_options['fields']['php_2']['element_type'] = 'div';
    $handler->display->display_options['fields']['php_2']['element_class'] = 'item-wrap';
    $handler->display->display_options['fields']['php_2']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php_2']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php_2']['php_output'] = '<?php

switch ($row->y_store_id) {
  case "yb":
    $url_path=\'.$bstore_path./\';
    break;
  case "yv":
    $url_path=\'.$vstore_path./\';
    break;
  case "yl":
    $url_path = \'.$lstore_path./\';
    break;
}

$current_img = \'\';
if(empty($row->lf_id)) {
  if(!empty($row->field_id)) {
    $current_product = commerce_product_load($row->field_id);
    $current_img = $current_product->field_id[\'und\'][0][\'value\'];
    $full_url = $url_path.$current_img.".html";
  } else {
   $current_img = \'\';
  }
} else {
  $current_img = $row->lf_id;
  $full_url = $url_path.$row->lf_id.".html";
}

print \'<div class="field-image"><a href="\'.$full_url.\'"><img src="https://images.".$vstore_path."/\' . $current_img . \'_im_100.jpg"></div>\';

?>';
    $handler->display->display_options['fields']['php_2']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php_2']['php_click_sortable'] = '';
    /* Field: Commerce Product: Options String */
    $handler->display->display_options['fields']['field_options_string']['id'] = 'field_options_string';
    $handler->display->display_options['fields']['field_options_string']['table'] = 'field_data_field_options_string';
    $handler->display->display_options['fields']['field_options_string']['field'] = 'field_options_string';
    $handler->display->display_options['fields']['field_options_string']['relationship'] = 'commerce_product_product_id';
    $handler->display->display_options['fields']['field_options_string']['label'] = '';
    $handler->display->display_options['fields']['field_options_string']['alter']['alter_text'] = TRUE;
    $handler->display->display_options['fields']['field_options_string']['alter']['text'] = '<div class="view-cart-item-title">[line_item_title]</div>
                            <div class="view-cart-item-code">[field_brand]</div>
                            <div class="options-string">[field_options_string]</div>';
    $handler->display->display_options['fields']['field_options_string']['element_type'] = 'div';
    $handler->display->display_options['fields']['field_options_string']['element_class'] = 'product-options';
    $handler->display->display_options['fields']['field_options_string']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_options_string']['empty'] = '<div class="view-cart-item-title">[line_item_title]</div>
                    <div class="view-cart-item-code">[field_brand]</div>';
    $handler->display->display_options['fields']['field_options_string']['type'] = 'yg_rendered_product_options';
    /* Field: Commerce Product: On sale */
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['id'] = 'field_commerce_saleprice_on_sale';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['table'] = 'field_data_field_commerce_saleprice_on_sale';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['field'] = 'field_commerce_saleprice_on_sale';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['relationship'] = 'commerce_product_product_id';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['label'] = '';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['exclude'] = TRUE;
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['element_type'] = '0';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['element_wrapper_type'] = '0';
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['field_commerce_saleprice_on_sale']['field_api_classes'] = TRUE;
    /* Field: Commerce Line item: Unit price */
    $handler->display->display_options['fields']['commerce_unit_price']['id'] = 'commerce_unit_price';
    $handler->display->display_options['fields']['commerce_unit_price']['table'] = 'field_data_commerce_unit_price';
    $handler->display->display_options['fields']['commerce_unit_price']['field'] = 'commerce_unit_price';
    $handler->display->display_options['fields']['commerce_unit_price']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['commerce_unit_price']['label'] = 'Price';
    $handler->display->display_options['fields']['commerce_unit_price']['alter']['alter_text'] = TRUE;
    $handler->display->display_options['fields']['commerce_unit_price']['alter']['text'] = '[php_1]
                                    [commerce_unit_price]';
    $handler->display->display_options['fields']['commerce_unit_price']['element_class'] = 'price';
    $handler->display->display_options['fields']['commerce_unit_price']['click_sort_column'] = 'amount';
    $handler->display->display_options['fields']['commerce_unit_price']['type'] = 'commerce_price_formatted_amount';
    $handler->display->display_options['fields']['commerce_unit_price']['settings'] = array(
        'calculation' => FALSE,
    );
    /* Field: Commerce Line Item: Form Field: Shipping */
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['id'] = 'commerce_line_item_shipping_field_line_item_shipping';
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['field'] = 'commerce_line_item_shipping_field_line_item_shipping';
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['label'] = 'Shipping';
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['exclude'] = TRUE;
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['commerce_line_item_shipping_field_line_item_shipping']['cart_form_hide_label'] = 1;
    /* Field: Commerce Line Item: Editable field for Extra Options */
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['id'] = 'yg_line_item_extra_field_line_item_extra_options';
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['field'] = 'yg_line_item_extra_field_line_item_extra_options';
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['label'] = '';
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['alter']['alter_text'] = TRUE;
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['alter']['text'] = '[commerce_line_item_shipping_field_line_item_shipping]
        [yg_line_item_extra_field_line_item_extra_options]';
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['yg_line_item_extra_field_line_item_extra_options']['cart_form_hide_label'] = 1;
    /* Field: Commerce Line Item: Quantity text field */
    $handler->display->display_options['fields']['edit_quantity']['id'] = 'edit_quantity';
    $handler->display->display_options['fields']['edit_quantity']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['edit_quantity']['field'] = 'edit_quantity';
    $handler->display->display_options['fields']['edit_quantity']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['edit_quantity']['label'] = 'Quantity';
    $handler->display->display_options['fields']['edit_quantity']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_quantity']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['edit_quantity']['alter']['ellipsis'] = FALSE;
    $handler->display->display_options['fields']['edit_quantity']['element_label_colon'] = FALSE;
    /* Field: Commerce Line Item: Delete button */
    $handler->display->display_options['fields']['edit_delete']['id'] = 'edit_delete';
    $handler->display->display_options['fields']['edit_delete']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['edit_delete']['field'] = 'edit_delete';
    $handler->display->display_options['fields']['edit_delete']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['edit_delete']['label'] = 'Remove';
    $handler->display->display_options['fields']['edit_delete']['exclude'] = TRUE;
    /* Field: Commerce Line Item: Move to Wishlist button */
    $handler->display->display_options['fields']['move_to_wishlist']['id'] = 'move_to_wishlist';
    $handler->display->display_options['fields']['move_to_wishlist']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['move_to_wishlist']['field'] = 'move_to_wishlist';
    $handler->display->display_options['fields']['move_to_wishlist']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['move_to_wishlist']['label'] = '';
    $handler->display->display_options['fields']['move_to_wishlist']['exclude'] = TRUE;
    $handler->display->display_options['fields']['move_to_wishlist']['element_label_colon'] = FALSE;
    /* Field: Global: Custom text */
    $handler->display->display_options['fields']['nothing_1']['id'] = 'nothing_1';
    $handler->display->display_options['fields']['nothing_1']['table'] = 'views';
    $handler->display->display_options['fields']['nothing_1']['field'] = 'nothing';
    $handler->display->display_options['fields']['nothing_1']['label'] = 'Quantity';
    $handler->display->display_options['fields']['nothing_1']['alter']['text'] = '[edit_quantity]
                [edit_delete]
                [move_to_wishlist]';
    $handler->display->display_options['fields']['nothing_1']['element_label_colon'] = FALSE;
    /* Field: Commerce Line item: Total */
    $handler->display->display_options['fields']['commerce_total']['id'] = 'commerce_total';
    $handler->display->display_options['fields']['commerce_total']['table'] = 'field_data_commerce_total';
    $handler->display->display_options['fields']['commerce_total']['field'] = 'commerce_total';
    $handler->display->display_options['fields']['commerce_total']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['commerce_total']['element_class'] = 'price';
    $handler->display->display_options['fields']['commerce_total']['click_sort_column'] = 'amount';
    $handler->display->display_options['fields']['commerce_total']['type'] = 'commerce_price_formatted_amount';
    /* Field: Content: Primary store */
    $handler->display->display_options['fields']['primary_store']['id'] = 'primary_store';
    $handler->display->display_options['fields']['primary_store']['table'] = 'node';
    $handler->display->display_options['fields']['primary_store']['field'] = 'primary_store';
    $handler->display->display_options['fields']['primary_store']['relationship'] = 'field_product';
    $handler->display->display_options['fields']['primary_store']['label'] = '';
    $handler->display->display_options['fields']['primary_store']['exclude'] = TRUE;
    $handler->display->display_options['fields']['primary_store']['element_label_colon'] = FALSE;
    /* Field: Commerce Line Item: Store ID */
    $handler->display->display_options['fields']['y_store_id']['id'] = 'y_store_id';
    $handler->display->display_options['fields']['y_store_id']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['y_store_id']['field'] = 'y_store_id';
    $handler->display->display_options['fields']['y_store_id']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['y_store_id']['label'] = '';
    $handler->display->display_options['fields']['y_store_id']['exclude'] = TRUE;
    $handler->display->display_options['fields']['y_store_id']['element_label_colon'] = FALSE;
    /* Sort criterion: Commerce Line Item: Line item ID */
    $handler->display->display_options['sorts']['line_item_id']['id'] = 'line_item_id';
    $handler->display->display_options['sorts']['line_item_id']['table'] = 'commerce_line_item';
    $handler->display->display_options['sorts']['line_item_id']['field'] = 'line_item_id';
    $handler->display->display_options['sorts']['line_item_id']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['sorts']['line_item_id']['order'] = 'DESC';
    /* Contextual filter: Commerce Order: Order ID */
    $handler->display->display_options['arguments']['order_id']['id'] = 'order_id';
    $handler->display->display_options['arguments']['order_id']['table'] = 'commerce_order';
    $handler->display->display_options['arguments']['order_id']['field'] = 'order_id';
    $handler->display->display_options['arguments']['order_id']['default_action'] = 'empty';
    $handler->display->display_options['arguments']['order_id']['default_argument_type'] = 'fixed';
    $handler->display->display_options['arguments']['order_id']['summary']['number_of_records'] = '0';
    $handler->display->display_options['arguments']['order_id']['summary']['format'] = 'default_summary';
    $handler->display->display_options['arguments']['order_id']['summary_options']['items_per_page'] = '25';
    /* Filter criterion: Commerce Line Item: Line item is of a product line item type */
    $handler->display->display_options['filters']['product_line_item_type']['id'] = 'product_line_item_type';
    $handler->display->display_options['filters']['product_line_item_type']['table'] = 'commerce_line_item';
    $handler->display->display_options['filters']['product_line_item_type']['field'] = 'product_line_item_type';
    $handler->display->display_options['filters']['product_line_item_type']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['filters']['product_line_item_type']['value'] = '1';
    $handler->display->display_options['filters']['product_line_item_type']['group'] = 0;

    /* Display: Page */
    $handler = $view->new_display('page', 'Page', 'page_1');
    $handler->display->display_options['defaults']['style_plugin'] = FALSE;
    $handler->display->display_options['style_plugin'] = 'views_json';
    $handler->display->display_options['style_options']['root_object'] = 'items';
    $handler->display->display_options['style_options']['top_child_object'] = 'item';
    $handler->display->display_options['style_options']['plaintext_output'] = 1;
    $handler->display->display_options['style_options']['remove_newlines'] = 0;
    $handler->display->display_options['style_options']['jsonp_prefix'] = '';
    $handler->display->display_options['style_options']['using_views_api_mode'] = 0;
    $handler->display->display_options['style_options']['object_arrays'] = 0;
    $handler->display->display_options['style_options']['numeric_strings'] = 0;
    $handler->display->display_options['style_options']['bigint_string'] = 0;
    $handler->display->display_options['style_options']['pretty_print'] = 1;
    $handler->display->display_options['style_options']['unescaped_slashes'] = 0;
    $handler->display->display_options['style_options']['unescaped_unicode'] = 0;
    $handler->display->display_options['style_options']['char_encoding'] = array();
    $handler->display->display_options['defaults']['style_options'] = FALSE;
    $handler->display->display_options['defaults']['row_plugin'] = FALSE;
    $handler->display->display_options['defaults']['row_options'] = FALSE;
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: LF_ID */
    $handler->display->display_options['fields']['lf_id']['id'] = 'lf_id';
    $handler->display->display_options['fields']['lf_id']['table'] = 'node';
    $handler->display->display_options['fields']['lf_id']['field'] = 'lf_id';
    $handler->display->display_options['fields']['lf_id']['relationship'] = 'field_product';
    $handler->display->display_options['fields']['lf_id']['label'] = 'id';
    $handler->display->display_options['fields']['lf_id']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['lf_id']['element_default_classes'] = FALSE;
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php']['id'] = 'php';
    $handler->display->display_options['fields']['php']['table'] = 'views';
    $handler->display->display_options['fields']['php']['field'] = 'php';
    $handler->display->display_options['fields']['php']['label'] = 'Add HTTP headers';
    $handler->display->display_options['fields']['php']['exclude'] = TRUE;
    $handler->display->display_options['fields']['php']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php']['use_php_setup'] = 1;
    $handler->display->display_options['fields']['php']['php_setup'] = 'if (!empty($_SERVER[\'HTTP_ORIGIN\'])) {
        $domain = parse_url($_SERVER[\'HTTP_ORIGIN\'], PHP_URL_HOST);
        if (preg_match("#y(living|bath|lighting)\\.com$#", $domain)) {
            drupal_add_http_header("Access-Control-Allow-Origin", $_SERVER[\'HTTP_ORIGIN\']);
            drupal_add_http_header("Access-Control-Allow-Credentials", "true");
        }
    }';
    $handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php']['php_click_sortable'] = '';
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php_1']['id'] = 'php_1';
    $handler->display->display_options['fields']['php_1']['table'] = 'views';
    $handler->display->display_options['fields']['php_1']['field'] = 'php';
    $handler->display->display_options['fields']['php_1']['label'] = 'Sale_price';
    $handler->display->display_options['fields']['php_1']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php_1']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['php_1']['hide_empty'] = TRUE;
    $handler->display->display_options['fields']['php_1']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php_1']['php_output'] = '<?php
$sale_price = $data->_field_data[\'commerce_product_field_data_commerce_product_product_id\'][\'entity\']->field_commerce_saleprice[\'und\'][0][\'amount\'];
if ($sale_price) {
    $cost_price = "$" . number_format(
        $data->_field_data[\'commerce_product_field_data_commerce_product_product_id\'][\'entity\']->field_commerce_saleprice[\'und\'][0][\'amount\'] * .01,
        2,
        \'.\',
        \',\'
    );

    print $cost_price;
}
print \'\';

 ?>';
    $handler->display->display_options['fields']['php_1']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php_1']['php_click_sortable'] = '';
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php_2']['id'] = 'php_2';
    $handler->display->display_options['fields']['php_2']['table'] = 'views';
    $handler->display->display_options['fields']['php_2']['field'] = 'php';
    $handler->display->display_options['fields']['php_2']['label'] = 'Image';
    $handler->display->display_options['fields']['php_2']['element_type'] = 'div';
    $handler->display->display_options['fields']['php_2']['element_class'] = 'item-wrap';
    $handler->display->display_options['fields']['php_2']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php_2']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php_2']['php_output'] = '<?php

switch ($row->y_store_id) {
  case "yb":
    $url_path=\'.$bstore_path./\';
    break;
  case "yv":
    $url_path=\'.$vstore_path./\';
    break;
  case "yl":
    $url_path = \'.$lstore_path./\';
    break;
}

$current_img = \'\';
if(empty($row->lf_id)) {
  if(!empty($row->field_id)) {
    $current_product = commerce_product_load($row->field_id);
    $current_img = $current_product->field_id[\'und\'][0][\'value\'];
    $full_url = $url_path.$current_img.".html";
  } else {
   $current_img = \'\';
  }
} else {
  $current_img = $row->lf_id;
  $full_url = $url_path.$row->lf_id.".html";
}

print \'https://images.$vstore_path\' . $current_img . \'_im_100.jpg\';

?>';
    $handler->display->display_options['fields']['php_2']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php_2']['php_click_sortable'] = '';
    /* Field: Commerce Product: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'commerce_product';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['relationship'] = 'commerce_product_product_id';
    $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['title']['link_to_product'] = 0;
    /* Field: Commerce Product: Options String */
    $handler->display->display_options['fields']['field_options_string']['id'] = 'field_options_string';
    $handler->display->display_options['fields']['field_options_string']['table'] = 'field_data_field_options_string';
    $handler->display->display_options['fields']['field_options_string']['field'] = 'field_options_string';
    $handler->display->display_options['fields']['field_options_string']['relationship'] = 'commerce_product_product_id';
    $handler->display->display_options['fields']['field_options_string']['label'] = '';
    $handler->display->display_options['fields']['field_options_string']['exclude'] = TRUE;
    $handler->display->display_options['fields']['field_options_string']['alter']['alter_text'] = TRUE;
    $handler->display->display_options['fields']['field_options_string']['alter']['text'] = '[field_options_string]';
    $handler->display->display_options['fields']['field_options_string']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_options_string']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['field_options_string']['hide_empty'] = TRUE;
    $handler->display->display_options['fields']['field_options_string']['hide_alter_empty'] = FALSE;
    $handler->display->display_options['fields']['field_options_string']['settings'] = array(
        'trim_length' => '600',
    );
    /* Field: Commerce Line item: Total */
    $handler->display->display_options['fields']['commerce_total']['id'] = 'commerce_total';
    $handler->display->display_options['fields']['commerce_total']['table'] = 'field_data_commerce_total';
    $handler->display->display_options['fields']['commerce_total']['field'] = 'commerce_total';
    $handler->display->display_options['fields']['commerce_total']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['commerce_total']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['commerce_total']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['commerce_total']['click_sort_column'] = 'amount';
    $handler->display->display_options['fields']['commerce_total']['type'] = 'commerce_price_formatted_amount';
    $handler->display->display_options['fields']['commerce_total']['settings'] = array(
        'calculation' => FALSE,
    );
    /* Field: Commerce Line Item: Quantity */
    $handler->display->display_options['fields']['quantity']['id'] = 'quantity';
    $handler->display->display_options['fields']['quantity']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['quantity']['field'] = 'quantity';
    $handler->display->display_options['fields']['quantity']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['quantity']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['quantity']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['quantity']['precision'] = '0';
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php_3']['id'] = 'php_3';
    $handler->display->display_options['fields']['php_3']['table'] = 'views';
    $handler->display->display_options['fields']['php_3']['field'] = 'php';
    $handler->display->display_options['fields']['php_3']['label'] = 'Options';
    $handler->display->display_options['fields']['php_3']['element_default_classes'] = FALSE;
    $handler->display->display_options['fields']['php_3']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php_3']['php_output'] = '<?php
$options = array();
foreach(explode("~~", $data->field_field_options_string[0][\'raw\'][\'value\']) as $option)
{
$options[] = str_replace("==", ": ", $option);
}
print implode("\\n", $options);
//print $value;
?>';
    $handler->display->display_options['fields']['php_3']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php_3']['php_click_sortable'] = '';
    /* Field: Commerce Line Item: Store ID */
    $handler->display->display_options['fields']['y_store_id']['id'] = 'y_store_id';
    $handler->display->display_options['fields']['y_store_id']['table'] = 'commerce_line_item';
    $handler->display->display_options['fields']['y_store_id']['field'] = 'y_store_id';
    $handler->display->display_options['fields']['y_store_id']['relationship'] = 'commerce_line_items_line_item_id';
    $handler->display->display_options['fields']['y_store_id']['label'] = 'store_id';
    $handler->display->display_options['fields']['y_store_id']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['y_store_id']['element_default_classes'] = FALSE;
    /* Field: Commerce Product: Sale price */
    $handler->display->display_options['fields']['field_commerce_saleprice']['id'] = 'field_commerce_saleprice';
    $handler->display->display_options['fields']['field_commerce_saleprice']['table'] = 'field_data_field_commerce_saleprice';
    $handler->display->display_options['fields']['field_commerce_saleprice']['field'] = 'field_commerce_saleprice';
    $handler->display->display_options['fields']['field_commerce_saleprice']['relationship'] = 'commerce_product_product_id';
    $handler->display->display_options['fields']['field_commerce_saleprice']['label'] = '';
    $handler->display->display_options['fields']['field_commerce_saleprice']['exclude'] = TRUE;
    $handler->display->display_options['fields']['field_commerce_saleprice']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['field_commerce_saleprice']['hide_empty'] = TRUE;
    $handler->display->display_options['fields']['field_commerce_saleprice']['empty_zero'] = TRUE;
    $handler->display->display_options['fields']['field_commerce_saleprice']['click_sort_column'] = 'amount';
    $handler->display->display_options['fields']['field_commerce_saleprice']['type'] = 'commerce_price_formatted_amount';
    $handler->display->display_options['fields']['field_commerce_saleprice']['settings'] = array(
        'calculation' => FALSE,
    );
    /* Field: Global: PHP */
    $handler->display->display_options['fields']['php_4']['id'] = 'php_4';
    $handler->display->display_options['fields']['php_4']['table'] = 'views';
    $handler->display->display_options['fields']['php_4']['field'] = 'php';
    $handler->display->display_options['fields']['php_4']['label'] = 'Price';
    $handler->display->display_options['fields']['php_4']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['php_4']['use_php_setup'] = 0;
    $handler->display->display_options['fields']['php_4']['php_output'] = '<?php
$cost_price = number_format($data->_field_data[\'commerce_product_field_data_commerce_product_product_id\'][\'entity\']->commerce_price[\'und\'][0][\'amount\'] * .01, 2, \'.\', \',\');
print "$" . $cost_price;
 ?>';
    $handler->display->display_options['fields']['php_4']['use_php_click_sortable'] = '0';
    $handler->display->display_options['fields']['php_4']['php_click_sortable'] = '';
    $handler->display->display_options['defaults']['arguments'] = FALSE;
    /* Contextual filter: Commerce Order: Order ID */
    $handler->display->display_options['arguments']['order_id']['id'] = 'order_id';
    $handler->display->display_options['arguments']['order_id']['table'] = 'commerce_order';
    $handler->display->display_options['arguments']['order_id']['field'] = 'order_id';
    $handler->display->display_options['arguments']['order_id']['default_action'] = 'default';
    $handler->display->display_options['arguments']['order_id']['default_argument_type'] = 'commerce_cart_current_cart_order_id';
    $handler->display->display_options['arguments']['order_id']['summary']['number_of_records'] = '0';
    $handler->display->display_options['arguments']['order_id']['summary']['format'] = 'default_summary';
    $handler->display->display_options['arguments']['order_id']['summary_options']['items_per_page'] = '25';
    $handler->display->display_options['path'] = 'cart.json';
    $translatables['cart_json'] = array(
        t('Defaults'),
        t('Shopping cart'),
        t('more'),
        t('Apply'),
        t('Reset'),
        t('Sort by'),
        t('Asc'),
        t('Desc'),
        t('Line Item'),
        t('Product'),
        t('Node referencing products from field_product'),
        t('View product'),
        t(' Item and options'),
        t('<div class="view-cart-item-title">[line_item_title]</div>
                            <div class="view-cart-item-code">[field_brand]</div>
                            <div class="options-string">[field_options_string]</div>'),
        t('<div class="view-cart-item-title">[line_item_title]</div>
                    <div class="view-cart-item-code">[field_brand]</div>'),
        t('Price'),
        t('[php_1]
                                    [commerce_unit_price]'),
        t('Shipping'),
        t('[commerce_line_item_shipping_field_line_item_shipping]
        [yg_line_item_extra_field_line_item_extra_options]'),
        t('Quantity'),
        t('Remove'),
        t('[edit_quantity]
                [edit_delete]
                [move_to_wishlist]'),
        t('Total'),
        t('All'),
        t('Page'),
        t('id'),
        t('Add HTTP headers'),
        t('Sale_price'),
        t('Image'),
        t('Title'),
        t('[field_options_string]'),
        t('.'),
        t(','),
        t('Options'),
        t('store_id'),
    );

    return array($view->name => $view);
}